# Generated by Django 4.2.11 on 2026-06-02 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0002_alter_purchaseorder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='current_payable_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total unpaid amount across all GRNs.', max_digits=14),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa Business'), ('cheque', 'Cheque')], default='bank_transfer', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('grn', models.ForeignKey(blank=True, help_text='Link to the specific GRN this payment settles (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='purchasing.goodsreceivednote')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchasing.supplier')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
