# Generated by Django 4.2.11 on 2026-06-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_financial_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date if purchased on credit', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='payment_term',
            field=models.CharField(choices=[('cash', 'Cash (Paid on Purchase)'), ('credit', 'Credit (Account)')], default='credit', max_length=20),
        ),
    ]
