# Generated by Django 4.2.11 on 2026-05-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_created_at_alter_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
