# Generated by Django 4.2.11 on 2026-05-08 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_staffprofile_branch_role_and_more'),
        ('sales', '0003_sale_currency_sale_customer_name_sale_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySaleCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(max_length=8)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counters', to='branches.branch')),
            ],
            options={
                'unique_together': {('branch', 'date_str')},
            },
        ),
    ]
