# Generated by Django 4.2.11 on 2026-05-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_dailysalecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='etims_submission_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
