# Generated by Django 4.2.11 on 2026-06-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='expected_card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='expected_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='expected_mpesa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='reported_card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='reported_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='reported_mpesa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
