# Generated by Django 4.2.11 on 2026-06-02 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0005_alter_sale_etims_submission_status'),
        ('customers', '0002_loyaltytier_customer_last_purchase_at_customer_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allow_credit_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Running outstanding balance. Positive = owes money.', max_digits=12),
        ),
        migrations.CreateModel(
            name='CustomerCreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('charge', 'Credit Purchase'), ('payment', 'Credit Repayment')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='M-Pesa receipt, bank ref, or cash receipt no.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='customers.customer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
