# Generated by Django 4.2.11 on 2026-05-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('store_credit', 'Store Credit'), ('bank_transfer', 'Bank Transfer'), ('points', 'Loyalty Points')], max_length=20),
        ),
    ]
