# Generated by Django 4.2.11 on 2026-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockmovement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('sale', 'Sale'), ('return', 'Return'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment'), ('spoilage', 'Spoilage'), ('expiry', 'Expiry'), ('theft', 'Theft'), ('damage', 'Damage'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('opening', 'Opening')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
