# Generated by Django 4.2.11 on 2026-05-07 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0002_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='branch_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('auditor', 'Auditor')], default='cashier', help_text='Effective role for this branch. Cannot exceed the TenantUser.role ceiling.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='staffprofile',
            unique_together={('user', 'branch')},
        ),
    ]
