# Generated by Django 4.2.11 on 2026-06-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_staffprofile_branch_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='mpesa_env',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='mpesa_passkey',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
